format = """
$directory\
$git_branch\
$git_status\
$git_state\
$python\
$character"""
add_newline = false

[directory]
style = "fg:11"
format = "[$path]($style)"
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ""
style = "fg:10"
format = "[:$branch]($style)"

[git_status]
format = "$modified$staged$untracked"

modified = "[ ●](fg:179)"
staged = "[ +](fg:10)"
untracked = "[ ●](fg:9)"

conflicted = ""
ahead = ""
behind = ""
diverged = ""
up_to_date = ""
renamed = ""
deleted = ""
stashed = ""

[git_state]
style = "fg:10"
format = " [($state)]($style)"

[python]
format = " via [$symbol$pyenv_prefix$version( \\($virtualenv\\))]($style)"

[character]
success_symbol = "[ \\$](white)"
error_symbol = "[ \\$](fg:9)"
